### ISSUE TITLE
local instance of annotator

### ISSUE THREAD

**Issue by ypriverol** [ncbo/ncbo_annotator#1]
@mdorf do you know if is possible to run a local instance of annotator?

**Comment by mdorf** [comment]
@ypriverol you cannot run a local instance of just the Annotator. You can run our entire platform, which includes the Annotator, by requesting the NCBO VM. You can request access to the VM by contacting us at support@bioontology.org.

**Comment by ypriverol** [comment]
@mdorf thanks for your support. I ask already for it and didn't get any reply. Can you help me on that direction? Also, We found that in the API the Post method give different results compare with the GET method?. Do you see any remote option to run annotator with an small set of ontologies via commnadline. ?

**Comment by graybeal** [comment]
For the record, we provided a copy of the Appliance to @ypriverol on July 5 (out of band).

For those of you looking for your own copy, please visit https://www.bioontology.org/wiki/index.php/Category:NCBO_Virtual_Appliance to learn what information to send the support@bioontology.org list if you want to expedite the request. If you send just a general request to that list, we respond privately (usually within a day) to ask for any additional information we need.
