### ISSUE TITLE
annotator cache generation failure - Unsupported command argument type: RDF::URI

### ISSUE THREAD

**Issue by alexskr** [ncbo/ncbo_annotator#26]
Annotator fails to create cache for a number of ontologies with an error `Unsupported command argument type: RDF::URI`

According to the parsing logs the annotator cache was generated successfully in the past but started to fail consistently.  This issue applies to both 4store (prod) and AG (stage) backends.

example ontologies: FOVT GSSO BMTO ONS PP PORO BSPO PLACES ECTO EDAMT VTO NeuroFMA NCI MMIRNAO DATASET MLTX PEAO ITO IOBC

`E, [2023-01-18T10:02:09.765678 #11136] ERROR -- : ["Unsupported command argument type: RDF::URI\n/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-client-0.11.2/lib/redis_client/command_builder.rb:75:in `block in generate'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-client-0.11.2/lib/redis_client/command_builder.rb:68:in `map!'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-client-0.11.2/lib/redis_client/command_builder.rb:68:in `generate'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-client-0.11.2/lib/redis_client.rb:218:in `call_v'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-5.0.5/lib/redis/client.rb:73:in `call_v'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-5.0.5/lib/redis.rb:167:in `block in send_command'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-5.0.5/lib/redis.rb:166:in `synchronize'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-5.0.5/lib/redis.rb:166:in `send_command'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/gems/redis-5.0.5/lib/redis/commands/hashes.rb:26:in `hset'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:676:in `create_term_entry'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:337:in `block (3 levels) in create_term_cache_for_submission'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:336:in `each'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:336:in `block (2 levels) in create_term_cache_for_submission'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:292:in `each'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:292:in `block in create_term_cache_for_submission'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:273:in `create_term_cache_for_submission'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:190:in `block in create_term_cache_from_ontologies'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:166:in `each_index'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:166:in `create_term_cache_from_ontologies'\n\t/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.7.0/bundler/gems/ncbo_annotator-71d41e3afb35/lib/ncbo_annotator.rb:106:in `create_term_cache'\n\tbin/ncbo_ontology_annotate_generate_cache:113:in `block in <top (required)>'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'\n\tbin/ncbo_ontology_annotate_generate_cache:112:in `<top (required)>'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'\n\t/usr/local/rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'\n\t/usr/local/rbenv/versions/2.7.6/bin/bundle:23:in `load'\n\t/usr/local/rbenv/versions/2.7.6/bin/bundle:23:in `<main>'"]
`

**Comment by mdorf** [comment]
I resolved this in the code; should go out in the next prod release.
